export type Product = {
  id: string;
  name: string;
  gender: "Women" | "Men";
  category: string;
  collection: string;
  price: number;
  originalPrice?: number;
  fabric: string;
  colors: string[];
  sizes: string[];
  image: string;
  altImage: string;
  sku: string;
  description: string;
  newArrival?: boolean;
  featured?: boolean;
  popular?: number;
};

const womenImages: [string, string, string] = [
  "/assets/editorial-heritage.jpg",
  "/assets/editorial-hero.jpg",
  "/assets/editorial-heritage.jpg",
];
const menImages: [string, string] = [
  "/assets/editorial-men.jpg",
  "/assets/editorial-men.jpg",
];

export const products: Product[] = [
  {
    id: "gulnaar-embroidered-set",
    name: "Gulnaar Embroidered Set",
    gender: "Women",
    category: "2 Piece",
    collection: "Signature",
    price: 7450,
    fabric: "Premium Lawn",
    colors: ["Magenta", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: womenImages[0],
    altImage: womenImages[1],
    sku: "MSC-W-101",
    description: "A refined two-piece silhouette scattered with delicate floral embroidery and finished with effortless tailoring.",
    newArrival: true,
    featured: true,
    popular: 98,
  },
  {
    id: "aasma-pearl-ensemble",
    name: "Aasma Pearl Ensemble",
    gender: "Women",
    category: "3 Piece",
    collection: "Summer",
    price: 10950,
    fabric: "Cotton Cambric",
    colors: ["Powder Blue", "Ivory"],
    sizes: ["S", "M", "L", "XL"],
    image: womenImages[1],
    altImage: womenImages[0],
    sku: "MSC-W-102",
    description: "An airy three-piece ensemble with pearl-white embroidery, wide trousers and a softly draped dupatta.",
    newArrival: true,
    featured: true,
    popular: 95,
  },
  {
    id: "mehrunnisa-noir",
    name: "Mehrunnisa Noir",
    gender: "Women",
    category: "Formal",
    collection: "Heritage",
    price: 18950,
    fabric: "Organza & Raw Silk",
    colors: ["Black", "Antique Gold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: womenImages[2],
    altImage: womenImages[0],
    sku: "MSC-W-103",
    description: "A statement formal ensemble rendered in black with antique gold embroidery inspired by archival motifs.",
    featured: true,
    popular: 100,
  },
  {
    id: "roshan-ivory",
    name: "Roshan Ivory",
    gender: "Women",
    category: "Luxury",
    collection: "Festive",
    price: 22950,
    fabric: "Jacquard",
    colors: ["Ivory", "Champagne"],
    sizes: ["S", "M", "L"],
    image: womenImages[0],
    altImage: womenImages[1],
    sku: "MSC-W-104",
    description: "Luminous jacquard and restrained handwork meet in an heirloom-inspired festive silhouette.",
    newArrival: true,
    popular: 89,
  },
  {
    id: "sahar-unstitched",
    name: "Sahar Unstitched",
    gender: "Women",
    category: "Unstitched",
    collection: "Summer",
    price: 5950,
    fabric: "Lawn",
    colors: ["Powder Blue", "White", "Olive"],
    sizes: ["Unstitched"],
    image: womenImages[1],
    altImage: womenImages[2],
    sku: "MSC-U-201",
    description: "Three-piece unstitched lawn: embroidered shirt 3m, printed dupatta 2.5m and dyed trouser 2.5m.",
    newArrival: true,
    popular: 83,
  },
  {
    id: "zareen-formal",
    name: "Zareen Formal",
    gender: "Women",
    category: "Shalwar Kameez",
    collection: "Luxury",
    price: 15950,
    originalPrice: 19950,
    fabric: "Silk",
    colors: ["Maroon", "Black"],
    sizes: ["XS", "S", "M", "L"],
    image: womenImages[2],
    altImage: womenImages[0],
    sku: "MSC-W-105",
    description: "A graceful silk shalwar kameez elevated with fine floral accents and clean contemporary lines.",
    popular: 91,
  },
  {
    id: "ayaan-ivory-kurta",
    name: "Ayaan Ivory Kurta Set",
    gender: "Men",
    category: "Shalwar Kameez",
    collection: "Signature",
    price: 8950,
    fabric: "Wash & Wear",
    colors: ["Ivory", "White", "Black"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: menImages[0],
    altImage: menImages[1],
    sku: "MSC-M-301",
    description: "An immaculately cut ivory kurta shalwar with a refined band collar and subtle tonal details.",
    newArrival: true,
    featured: true,
    popular: 99,
  },
  {
    id: "sarmad-olive-waistcoat",
    name: "Sarmad Olive Waistcoat Set",
    gender: "Men",
    category: "Waistcoat",
    collection: "Heritage",
    price: 12950,
    fabric: "Blended Karandi",
    colors: ["Olive", "Charcoal"],
    sizes: ["S", "M", "L", "XL"],
    image: menImages[1],
    altImage: menImages[0],
    sku: "MSC-M-302",
    description: "A deep olive kurta shalwar paired with a charcoal waistcoat for understated ceremonial dressing.",
    featured: true,
    popular: 94,
  },
  {
    id: "faris-charcoal",
    name: "Faris Charcoal Kurta",
    gender: "Men",
    category: "Kurta",
    collection: "Festive",
    price: 7450,
    fabric: "Cotton Satin",
    colors: ["Charcoal", "Navy"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    image: menImages[0],
    altImage: menImages[1],
    sku: "MSC-M-303",
    description: "A contemporary straight kurta with restrained tonal threadwork and an elegant evening finish.",
    newArrival: true,
    popular: 87,
  },
  {
    id: "safed-classic",
    name: "Safed Classic",
    gender: "Men",
    category: "Formal",
    collection: "Luxury",
    price: 9950,
    originalPrice: 11950,
    fabric: "Egyptian Cotton",
    colors: ["White", "Ivory"],
    sizes: ["S", "M", "L", "XL"],
    image: menImages[1],
    altImage: menImages[0],
    sku: "MSC-M-304",
    description: "Pure white formal tailoring designed for impeccable drape, comfort and timeless occasion wear.",
    popular: 90,
  },
  {
    id: "raees-unstitched",
    name: "Raees Unstitched Suiting",
    gender: "Men",
    category: "Unstitched",
    collection: "Winter",
    price: 4950,
    fabric: "Premium Wool Blend",
    colors: ["Brown", "Grey", "Navy"],
    sizes: ["4.5 Metres"],
    image: menImages[0],
    altImage: menImages[1],
    sku: "MSC-M-305",
    description: "A 4.5 metre premium suiting cut with a soft hand, elegant fall and enduring winter weight.",
    popular: 78,
  },
  {
    id: "eid-noir",
    name: "Eid Noir Waistcoat",
    gender: "Men",
    category: "Festive",
    collection: "Eid",
    price: 10950,
    originalPrice: 13950,
    fabric: "Jacquard",
    colors: ["Black", "Gold"],
    sizes: ["S", "M", "L", "XL"],
    image: menImages[1],
    altImage: menImages[0],
    sku: "MSC-M-306",
    description: "A dark jacquard waistcoat with tonal patterning, made for polished Eid and wedding dressing.",
    newArrival: true,
    popular: 86,
  },
];

export const colorValue: Record<string, string> = {
  Magenta: "#a20c5d",
  Ivory: "#f2eadc",
  "Powder Blue": "#9fb9ca",
  Black: "#171717",
  "Antique Gold": "#a9803f",
  Champagne: "#d9c7a2",
  White: "#fafafa",
  Olive: "#59633a",
  Maroon: "#6d1728",
  Charcoal: "#363635",
  Navy: "#1d2c45",
  Brown: "#6b4934",
  Grey: "#8a8985",
  Gold: "#b78c38",
};

export const formatPrice = (value: number) => `PKR ${value.toLocaleString("en-PK")}`;

export const collectionCopy: Record<string, string> = {
  Signature: "Quietly confident silhouettes that define the MS point of view.",
  Heritage: "Archival motifs and enduring craft, interpreted for today.",
  Festive: "Luminous textures and considered details for every celebration.",
  Luxury: "Exceptional fabrics, hand-finished for rare occasions.",
  Summer: "Breathable colour and light-as-air ease for warmer days.",
  Winter: "Rich textures and tailored layers with an elegant fall.",
  Eid: "Celebratory dressing imbued with grace and modern restraint.",
  "New Arrivals": "The newest chapter of considered Pakistani dressing.",
};
