export type Product = {
  id: string;
  name: string;
  gender: "Women" | "Men";
  category: string;
  collection: string;
  price: number; // Stitched price (or standard price for men)
  unstitchedPrice?: number; // Unstitched fabric price
  originalPrice?: number;
  fabric: string;
  colors: string[];
  sizes: string[];
  image: string;
  altImage: string;
  sku: string;
  description: string;
  isStitched: boolean;
  newArrival?: boolean;
  featured?: boolean;
  popular?: number;
};

const menImages: readonly string[] = [
  "/images/products/men/01.jfif",
  "/images/products/men/02.jfif",
  "/images/products/men/03.jfif",
];

// ── Women's Catalog ──────────────────────────────────────────────────────────
export const womenCatalog: Product[] = [
  {
    id: "embroidered-lawn-suit-01",
    name: "Winter 2 Piece Suit",
    gender: "Women",
    category: "2 Piece",
    collection: "Signature",
    price: 4300,
    unstitchedPrice: 2800,
    fabric: "Winter Stuff",
    colors: ["Ivory", "Gold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/01.jfif",
    altImage: "/images/products/women/01.jfif",
    sku: "MSC-W-101",
    description: "Beautiful 2-piece winter suit. Available both Stitched and Unstitched.",
    isStitched: true,
    newArrival: true,
    featured: true,
    popular: 98,
  },
  {
    id: "printed-lawn-suit-02",
    name: "Winter 2 Piece Suit",
    gender: "Women",
    category: "2 Piece",
    collection: "Summer",
    price: 4300,
    unstitchedPrice: 2800,
    fabric: "Winter Stuff",
    colors: ["Powder Blue", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/02.jfif",
    altImage: "/images/products/women/02.jfif",
    sku: "MSC-W-102",
    description: "Vibrant 2-piece winter suit. Available Stitched or Unstitched.",
    isStitched: true,
    newArrival: true,
    popular: 95,
  },
  {
    id: "linen-suit-03",
    name: "Linen 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Summer",
    price: 4000,
    unstitchedPrice: 2500,
    fabric: "Linen",
    colors: ["Magenta", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/03.jfif",
    altImage: "/images/products/women/03.jfif",
    sku: "MSC-W-103",
    description: "Elegant 3-piece linen suit — breathable and stylish for all occasions. Available Stitched or Unstitched.",
    isStitched: true,
    newArrival: true,
    popular: 89,
  },
  {
    id: "khaddar-suit-04",
    name: "Khaddar 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Signature",
    price: 5000,
    unstitchedPrice: 3500,
    fabric: "Khaddar",
    colors: ["Black", "Gold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/04.jfif",
    altImage: "/images/products/women/04.jfif",
    sku: "MSC-W-104",
    description: "Beautiful 3-piece khaddar suit with premium fabric quality. Available Stitched or Unstitched.",
    isStitched: true,
    featured: true,
    popular: 94,
  },
  {
    id: "3piece-suit-05",
    name: "Khaddar 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Festive",
    price: 5000,
    unstitchedPrice: 3500,
    fabric: "Khaddar",
    colors: ["Ivory", "Champagne"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/05.jfif",
    altImage: "/images/products/women/05.jfif",
    sku: "MSC-W-105",
    description: "Elegant 3-piece khaddar suit with premium fabric and beautiful design. Available Stitched or Unstitched.",
    isStitched: true,
    featured: true,
    popular: 97,
  },
  {
    id: "3piece-suit-06",
    name: "Khaddar 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Heritage",
    price: 5000,
    unstitchedPrice: 3500,
    fabric: "Khaddar",
    colors: ["Black", "Maroon"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/06.jfif",
    altImage: "/images/products/women/06.jfif",
    sku: "MSC-W-106",
    description: "Stunning 3-piece khaddar suit with premium fabric and elegant styling. Available Stitched or Unstitched.",
    isStitched: true,
    featured: true,
    popular: 99,
  },
  {
    id: "linen-suit-07",
    name: "Linen 2 Piece Suit",
    gender: "Women",
    category: "2 Piece",
    collection: "Summer",
    price: 4300,
    unstitchedPrice: 2800,
    fabric: "Linen",
    colors: ["Olive", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/07.jfif",
    altImage: "/images/products/women/07.jfif",
    sku: "MSC-W-107",
    description: "Comfortable 2-piece linen suit — light and breathable for everyday wear. Available Stitched or Unstitched.",
    isStitched: true,
    newArrival: true,
    popular: 90,
  },
  {
    id: "dhanak-suit-08",
    name: "Dhanak 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Luxury",
    price: 6500,
    unstitchedPrice: 5000,
    fabric: "Dhanak",
    colors: ["Navy", "Charcoal"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/08.jfif",
    altImage: "/images/products/women/08.jfif",
    sku: "MSC-W-108",
    description: "Premium 3-piece dhanak suit — warm, soft and perfect for winter. Available Stitched or Unstitched.",
    isStitched: true,
    popular: 93,
  },
  {
    id: "dhanak-suit-09",
    name: "Dhanak 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Festive",
    price: 6500,
    unstitchedPrice: 5000,
    fabric: "Dhanak",
    colors: ["Gold", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/09.jfif",
    altImage: "/images/products/women/09.jfif",
    sku: "MSC-W-109",
    description: "Beautiful 3-piece dhanak suit with elegant design and soft fabric. Available Stitched or Unstitched.",
    isStitched: true,
    popular: 88,
  },

  {
    id: "khaddar-suit-12",
    name: "Khaddar 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Festive",
    price: 5000,
    unstitchedPrice: 3500,
    fabric: "Khaddar",
    colors: ["Champagne", "Antique Gold"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/12.jfif",
    altImage: "/images/products/women/12.jfif",
    sku: "MSC-W-112",
    description: "Premium 3-piece khaddar suit with rich fabric quality and beautiful design. Available Stitched or Unstitched.",
    isStitched: true,
    featured: true,
    popular: 96,
  },
  {
    id: "khaddar-suit-13",
    name: "Khaddar 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Signature",
    price: 5000,
    unstitchedPrice: 3500,
    fabric: "Khaddar",
    colors: ["Olive", "White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/13.jfif",
    altImage: "/images/products/women/13.jfif",
    sku: "MSC-W-113",
    description: "Elegant 3-piece khaddar suit with quality fabric and refined design. Available Stitched or Unstitched.",
    isStitched: true,
    popular: 87,
  },
  {
    id: "dhanak-suit-14",
    name: "Dhanak 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Summer",
    price: 6500,
    unstitchedPrice: 5000,
    fabric: "Dhanak",
    colors: ["White", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/14.jfif",
    altImage: "/images/products/women/14.jfif",
    sku: "MSC-W-114",
    description: "Soft and warm 3-piece dhanak suit — ideal for winter wear. Available Stitched or Unstitched.",
    isStitched: true,
    newArrival: true,
    popular: 94,
  },
  {
    id: "dhanak-suit-15",
    name: "Dhanak 3 Piece Suit",
    gender: "Women",
    category: "3 Piece",
    collection: "Luxury",
    price: 6500,
    unstitchedPrice: 5000,
    fabric: "Dhanak",
    colors: ["Magenta", "Ivory"],
    sizes: ["XS", "S", "M", "L", "XL"],
    image: "/images/products/women/15.jfif",
    altImage: "/images/products/women/15.jfif",
    sku: "MSC-W-115",
    description: "Luxurious 3-piece dhanak suit with premium quality fabric and beautiful styling. Available Stitched or Unstitched.",
    isStitched: true,
    newArrival: true,
    popular: 97,
  },
];

// ── Men's Catalog ────────────────────────────────────────────────────────────
export const menCatalog: Product[] = [
  {
    id: "ayaan-ivory-kurta",
    name: "Ivory Shalwar Kameez",
    gender: "Men",
    category: "Shalwar Kameez",
    collection: "Signature",
    price: 2800,
    fabric: "Wash & Wear",
    colors: ["Ivory", "White", "Black"],
    sizes: [],
    image: menImages[0],
    altImage: menImages[1],
    sku: "MSC-M-301",
    description: "Premium unstitched shalwar kameez fabric in ivory wash & wear.",
    isStitched: false,
    newArrival: true,
    featured: true,
    popular: 99,
  },
  {
    id: "sarmad-olive-suit",
    name: "Olive Shalwar Kameez",
    gender: "Men",
    category: "Shalwar Kameez",
    collection: "Signature",
    price: 2800,
    fabric: "Karandi",
    colors: ["Olive", "Charcoal"],
    sizes: [],
    image: menImages[1],
    altImage: menImages[2],
    sku: "MSC-M-302",
    description: "Premium unstitched karandi shalwar kameez fabric in olive shade.",
    isStitched: false,
    featured: true,
    popular: 94,
  },
  {
    id: "faris-charcoal",
    name: "Charcoal Shalwar Kameez",
    gender: "Men",
    category: "Shalwar Kameez",
    collection: "Signature",
    price: 2800,
    fabric: "Cotton Satin",
    colors: ["Charcoal", "Navy"],
    sizes: [],
    image: menImages[2],
    altImage: menImages[0],
    sku: "MSC-M-303",
    description: "Premium unstitched cotton satin shalwar kameez fabric in charcoal shade.",
    isStitched: false,
    newArrival: true,
    popular: 87,
  },
];

// Combine all products for default queries
export const products: Product[] = [...womenCatalog, ...menCatalog];

export const colorValue: Record<string, string> = {
  Magenta: "#a20c5d",
  Ivory: "#f2eadc",
  "Powder Blue": "#9fb9ca",
  Black: "#171717",
  "Antique Gold": "#a9803f",
  Champagne: "#d9c7a2",
  White: "#fafafa",
  Olive: "#59633a",
  Maroon: "#6d1728",
  Charcoal: "#363635",
  Navy: "#1d2c45",
  Brown: "#6b4934",
  Grey: "#8a8985",
  Gold: "#b78c38",
};

export const formatPrice = (value: number) => `PKR ${value.toLocaleString("en-PK")}`;

export const collectionCopy: Record<string, string> = {
  Signature: "Quietly confident silhouettes that define the MS point of view.",
  Heritage: "Archival motifs and enduring craft, interpreted for today.",
  Festive: "Luminous textures and considered details for every celebration.",
  Luxury: "Exceptional fabrics, hand-finished for rare occasions.",
  Summer: "Breathable colour and light-as-air ease for warmer days.",
  Winter: "Rich textures and tailored layers with an elegant fall.",
  Eid: "Celebratory dressing imbued with grace and modern restraint.",
  "New Arrivals": "The newest chapter of considered Pakistani dressing.",
};
